site_name: Former documentation
repo_url: https://github.com/kennethnym/former
repo_name: kennethnym/former

theme:
  name: material
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  version:
    provider: mike